# Generated by Django 5.2.4 on 2025-07-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclubproject', '0003_alter_book_authors_alter_book_avg_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
