# Generated by Django 5.2.4 on 2025-07-12 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('bookclubproject', '0004_alter_book_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('books_to_read', models.ManyToManyField(related_name='added_to_reading_list_by', to='bookclubproject.book')),
                ('favorite_books', models.ManyToManyField(related_name='favorited_by', to='bookclubproject.book')),
            ],
        ),
    ]
