# Generated by Django 5.2.4 on 2025-07-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclubproject', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='books_to_read',
            field=models.ManyToManyField(blank=True, related_name='added_to_reading_list_by', to='bookclubproject.book'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorite_books',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='bookclubproject.book'),
        ),
    ]
